# Минимальная версия iOS теперь 15.5 (требование GoogleMLKit)
platform :ios, '15.5'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # Минимальная версия iOS
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'

      # Включаем модули
      config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'

      # Фикс arm64 (ВАЖНО для твоей ошибки)
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'

      # Для старых библиотек
      if target.name.include?('PromisesObjC') ||
         target.name.include?('GTMSessionFetcher') ||
         target.name.include?('GoogleToolboxForMac')
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
      end

      # Для mobile_scanner
      if target.name.include?('mobile_scanner')
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end

  # Fix build dir
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)'
      end
    end
  end
end
